// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ByteStoreWebService {
	
	
	public partial class PaginaPrueba {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.MultiView MultiViewMain;
		
		protected System.Web.UI.WebControls.View ViewGral;
		
		protected System.Web.UI.WebControls.Button btnUsuarios;
		
		protected System.Web.UI.WebControls.Button btnDevelopers;
		
		protected System.Web.UI.WebControls.Button btnApps;
		
		protected System.Web.UI.WebControls.Button btnEtc;
		
		protected System.Web.UI.WebControls.DataGrid DataGridUsuarios;
		
		protected System.Web.UI.WebControls.DataGrid DataGridDevelopers;
		
		protected System.Web.UI.WebControls.DataGrid DataGridApps;
		
		protected System.Web.UI.WebControls.DataGrid DataGridHistorial;
		
		protected System.Web.UI.WebControls.View ViewUsuarios;
		
		protected System.Web.UI.WebControls.Label Label1;
		
		protected System.Web.UI.WebControls.TextBox txtUsuario;
		
		protected System.Web.UI.WebControls.Label Label2;
		
		protected System.Web.UI.WebControls.TextBox txtPassword;
		
		protected System.Web.UI.WebControls.Label Label3;
		
		protected System.Web.UI.WebControls.TextBox txtNombre;
		
		protected System.Web.UI.WebControls.Label Label4;
		
		protected System.Web.UI.WebControls.TextBox txtCorreo;
		
		protected System.Web.UI.WebControls.Button btnAltaUsuario;
		
		protected System.Web.UI.WebControls.View ViewDevelopers;
		
		protected System.Web.UI.WebControls.Label Label6;
		
		protected System.Web.UI.WebControls.TextBox txtPasswordDev;
		
		protected System.Web.UI.WebControls.Label Label7;
		
		protected System.Web.UI.WebControls.TextBox txtNombreDev;
		
		protected System.Web.UI.WebControls.Label Label8;
		
		protected System.Web.UI.WebControls.TextBox txtApellidoDev;
		
		protected System.Web.UI.WebControls.Label Label5;
		
		protected System.Web.UI.WebControls.TextBox txtCorreoDev;
		
		protected System.Web.UI.WebControls.Label Label9;
		
		protected System.Web.UI.WebControls.TextBox txtGrupo;
		
		protected System.Web.UI.WebControls.Label lblRespuestaDev;
		
		protected System.Web.UI.WebControls.Button btnEnlistarseDev;
		
		protected System.Web.UI.WebControls.View ViewApps;
		
		protected System.Web.UI.WebControls.Label Label10;
		
		protected System.Web.UI.WebControls.TextBox txtNombreApp;
		
		protected System.Web.UI.WebControls.Label Label11;
		
		protected System.Web.UI.WebControls.TextBox txtVersionApp;
		
		protected System.Web.UI.WebControls.Label Label12;
		
		protected System.Web.UI.WebControls.TextBox txtUrlApp;
		
		protected System.Web.UI.WebControls.Label Label13;
		
		protected System.Web.UI.WebControls.TextBox txtDescripcionApp;
		
		protected System.Web.UI.WebControls.Label Label15;
		
		protected System.Web.UI.WebControls.FileUpload FileUploadIcono;
		
		protected System.Web.UI.WebControls.Label Label16;
		
		protected System.Web.UI.WebControls.FileUpload FileUploadImg1;
		
		protected System.Web.UI.WebControls.Label Label17;
		
		protected System.Web.UI.WebControls.FileUpload FileUploadImg2;
		
		protected System.Web.UI.WebControls.Label Label18;
		
		protected System.Web.UI.WebControls.FileUpload FileUploadImg3;
		
		protected System.Web.UI.WebControls.Button btnSubirApp;
	}
}
